In [17]:
from sklearn import metrics
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, f1_score, precision_score,classification_report, recall_score, confusion_matrix
from matplotlib import pyplot as plt
from sklearn  import preprocessing
import numpy as np
from sklearn.metrics import classification_report
from sklearn.linear_model import LogisticRegression
import sklearn
import matplotlib.pyplot as plt
from matplotlib import style
style.use("ggplot")
import pandas as pd
from sklearn.decomposition import PCA
#from sklearn.decomposition import RandomizedPCA
from sklearn import metrics
from sklearn import svm
from sklearn.svm import SVC
#from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score, classification_report, confusion_matrix
#import numpy as np
import pylab as pl
from PIL import Image
import os
from sklearn.ensemble import RandomForestClassifier
from sklearn.neural_network import MLPClassifier

In [18]:
#print("aaa")

COMMON_SIZE = (100, 100)
def image_to_matrix(filename):
	"""
	takes a filename and turns it into a numpy array of RGB pixels
	"""
	img = Image.open(filename)
	img = img.resize(COMMON_SIZE)
	img = np.asarray(img)
	return img

def flatten_matrix(matrix):
	"""
	takes in an (m, n) numpy array and flattens it
	into an array of shape (1, m * n * 3)
	"""
	s = matrix.shape[0] * matrix.shape[1] * 3
	mat = matrix.reshape(1,s)
	#print(mat.shape)
	return mat[0]
#60:30:10
#01
classes = ['Good', 'Peaberry']
#32_32 image pixel
#train_image_dirs = ["C:/Users/Hira/Desktop/Coffee_2019_13032020/32_32/Coffee_2019/Train/Good/", "C:/Users/Hira/Desktop/Coffee_2019_13032020/32_32/Coffee_2019/Train/Peaberry/"]
#64_64 image pixel
#train_image_dirs = ["C:/Users/Hira/Desktop/Coffee_2019_13032020/64_64/Coffee_2019/Train/Good/", "C:/Users/Hira/Desktop/Coffee_2019_13032020/64_64/Coffee_2019/Train/Peaberry/"]
#128_128 image pixel
#train_image_dirs = ["C:/Users/Hira/Desktop/Coffee_2019_13032020/128_128/Coffee_2019/Train/Good/", "C:/Users/Hira/Desktop/Coffee_2019_13032020/128_128/Coffee_2019/Train/Peaberry/"]
#256_256 image pixel
train_image_dirs = ["C:/Users/Hira/Desktop/Coffee_2019_13032020/256_256/Coffee_2019/Train/Good/", "C:/Users/Hira/Desktop/Coffee_2019_13032020/256_256/Coffee_2019/Train/Peaberry/"]

train_images = []
train_labels = []
# Retrieval of path of all pictures from "train" folder
for directory in train_image_dirs:
	temp_list = [directory+ f for f in os.listdir(directory)]
	train_labels.extend(len(temp_list)*[classes[train_image_dirs.index(directory)]])
	train_images.extend(temp_list)

# Creation of the whole training dataset
train_data = []
for image in train_images:
	image = image_to_matrix(image)
	image = flatten_matrix(image)
	train_data.append(image)
train_data = np.array(train_data)

# Creation of the whole test set
test_labels = []

#60:30:10
#32_32 image pixel
#test_image_dirs = ["C:/Users/Hira/Desktop/Coffee_2019_13032020/32_32/Coffee_2019/Test/Good/", "C:/Users/Hira/Desktop/Coffee_2019_13032020/32_32/Coffee_2019/Test/Peaberry/"]
#64_64 image pixel
#test_image_dirs = ["C:/Users/Hira/Desktop/Coffee_2019_13032020/64_64/Coffee_2019/Test/Good/", "C:/Users/Hira/Desktop/Coffee_2019_13032020/64_64/Coffee_2019/Test/Peaberry/"]
#128_128 image pixel
#test_image_dirs = ["C:/Users/Hira/Desktop/Coffee_2019_13032020/128_128/Coffee_2019/Test/Good/", "C:/Users/Hira/Desktop/Coffee_2019_13032020/128_128/Coffee_2019/Test/Peaberry/"]
#256_256 image pixel
test_image_dirs = ["C:/Users/Hira/Desktop/Coffee_2019_13032020/256_256/Coffee_2019/Test/Good/", "C:/Users/Hira/Desktop/Coffee_2019_13032020/256_256/Coffee_2019/Test/Peaberry/"]

test_images = []
for directory in test_image_dirs:
	temp_list = [directory+ f for f in os.listdir(directory)]
	test_labels.extend(len(temp_list)*[classes[test_image_dirs.index(directory)]])
	test_images.extend(temp_list)

test_data = []
for image in test_images:
	image = image_to_matrix(image)
	image = flatten_matrix(image)
	test_data.append(image)
test_data = np.array(test_data)

In [22]:
#Support Vector Machine (SVM) 

In [19]:
#Linear SVM
clf = svm.SVC(kernel = 'linear',gamma = 50, C=1)

#non-linear SVM
#clf = svm.NuSVC(nu=0.4, kernel="rbf", gamma=0.1)
#clf = svm.NuSVC(gamma='auto')
clf.fit(train_data, train_labels)
print("SVM average score: %f" % clf.score(test_data, test_labels))

predicted_label = clf.predict(test_data)

Accuracy_Score = accuracy_score(test_labels, predicted_label)
Precision_Score = precision_score(test_labels, predicted_label,  average="macro")
Recall_Score = recall_score(test_labels, predicted_label,  average="macro")
F1_Score = f1_score(test_labels, predicted_label,  average="macro")

print('Average Accuracy: %0.2f +/- (%0.1f) %%' % (Accuracy_Score.mean()*100, Accuracy_Score.std()*100))
print('Average Precision: %0.2f +/- (%0.1f) %%' % (Precision_Score.mean()*100, Precision_Score.std()*100))
print('Average Recall: %0.2f +/- (%0.1f) %%' % (Recall_Score.mean()*100, Recall_Score.std()*100))
print('Average F1-Score: %0.2f +/- (%0.1f) %%' % (F1_Score.mean()*100, F1_Score.std()*100))

print("")
#https://en.wikipedia.org/wiki/Confusion_matrix
CM = confusion_matrix(test_labels, predicted_label)

print ('Confusion Matrix :')
print(CM)
for i in predicted_label:
	print(i)	   

SVM average score: 0.964072


ValueError: Error when checking input: expected dense_3_input to have shape (15,) but got array with shape (30000,)

In [65]:
#K-Nearest-Neighbor (KNN) 

In [56]:
#kn = KNeighborsClassifier(n_neighbors =1)
#kn = KNeighborsClassifier(n_neighbors =2)
#kn = KNeighborsClassifier(n_neighbors =3)
#kn = KNeighborsClassifier(n_neighbors =4)
#kn = KNeighborsClassifier(n_neighbors =5)
#kn = KNeighborsClassifier(n_neighbors =6)
#kn = KNeighborsClassifier(n_neighbors =7)
#kn = KNeighborsClassifier(n_neighbors =8)
#kn = KNeighborsClassifier(n_neighbors =9)
kn = KNeighborsClassifier(n_neighbors =10)
kn.fit(train_data, train_labels)

print("KNN average score: %f" % kn.score(test_data, test_labels))
print("")

predicted_label = kn.predict(test_data)

Accuracy_Score = accuracy_score(test_labels, predicted_label)
Precision_Score = precision_score(test_labels, predicted_label,  average="macro")
Recall_Score = recall_score(test_labels, predicted_label,  average="macro")
F1_Score = f1_score(test_labels, predicted_label,  average="macro")

print('Average Accuracy: %0.2f +/- (%0.1f) %%' % (Accuracy_Score.mean()*100, Accuracy_Score.std()*100))
print('Average Precision: %0.2f +/- (%0.1f) %%' % (Precision_Score.mean()*100, Precision_Score.std()*100))
print('Average Recall: %0.2f +/- (%0.1f) %%' % (Recall_Score.mean()*100, Recall_Score.std()*100))
print('Average F1-Score: %0.2f +/- (%0.1f) %%' % (F1_Score.mean()*100, F1_Score.std()*100))

print("")
#https://en.wikipedia.org/wiki/Confusion_matrix
CM = confusion_matrix(test_labels, predicted_label)

print ('Confusion Matrix :')
print(CM)

for i in predicted_label:
	print(i)	   

KNN average score: 0.946108

Average Accuracy: 94.61 +/- (0.0) %
Average Precision: 95.01 +/- (0.0) %
Average Recall: 94.09 +/- (0.0) %
Average F1-Score: 94.45 +/- (0.0) %

Confusion Matrix :
[[186   4]
 [ 14 130]]
Good
Good
Good
Good
Good
Good
Good
Good
Good
Good
Good
Good
Good
Good
Good
Good
Good
Good
Good
Good
Good
Good
Good
Good
Good
Good
Good
Good
Good
Good
Good
Good
Good
Good
Good
Good
Good
Good
Good
Good
Good
Good
Good
Good
Good
Good
Good
Good
Good
Good
Good
Good
Good
Good
Good
Good
Good
Good
Peaberry
Good
Good
Good
Good
Peaberry
Good
Good
Good
Good
Good
Good
Good
Good
Good
Good
Good
Good
Good
Good
Good
Good
Good
Good
Good
Good
Good
Good
Good
Good
Good
Good
Good
Good
Good
Good
Good
Good
Good
Good
Good
Good
Good
Peaberry
Good
Good
Good
Good
Good
Good
Good
Good
Good
Good
Good
Good
Good
Good
Good
Good
Good
Good
Good
Good
Good
Peaberry
Good
Good
Good
Good
Good
Good
Good
Good
Good
Good
Good
Good
Good
Good
Good
Good
Good
Good
Good
Good
Good
Good
Good
Good
Good
Good
Good
Good
Good
Good

In [47]:
#Logistic Regression (LOG)

In [72]:
log = LogisticRegression(solver="lbfgs", multi_class="auto")
log.fit(train_data, train_labels)
print("LOG average score: %f" % log.score(test_data, test_labels))
#print("")

predicted_label = log.predict(test_data)

Accuracy_Score = accuracy_score(test_labels, predicted_label)
Precision_Score = precision_score(test_labels, predicted_label,  average="macro")
Recall_Score = recall_score(test_labels, predicted_label,  average="macro")
F1_Score = f1_score(test_labels, predicted_label,  average="macro")

print('Average Accuracy: %0.2f +/- (%0.1f) %%' % (Accuracy_Score.mean()*100, Accuracy_Score.std()*100))
print('Average Precision: %0.2f +/- (%0.1f) %%' % (Precision_Score.mean()*100, Precision_Score.std()*100))
print('Average Recall: %0.2f +/- (%0.1f) %%' % (Recall_Score.mean()*100, Recall_Score.std()*100))
print('Average F1-Score: %0.2f +/- (%0.1f) %%' % (F1_Score.mean()*100, F1_Score.std()*100))

print("")
#https://en.wikipedia.org/wiki/Confusion_matrix
CM = confusion_matrix(test_labels, predicted_label)

print(CM)

for i in predicted_label:
	print(i)	   


LOG average score: 0.846690
Average Accuracy: 84.67 +/- (0.0) %
Average Precision: 81.49 +/- (0.0) %
Average Recall: 84.07 +/- (0.0) %
Average F1-Score: 82.50 +/- (0.0) %

[[ 71  15]
 [ 29 172]]
Good_Front
Good_Front
Good_Front
Good_Front
Good_Front
Good_Back
Good_Front
Good_Back
Good_Back
Good_Front
Good_Front
Good_Front
Good_Front
Good_Front
Good_Front
Good_Back
Good_Back
Good_Front
Good_Back
Good_Front
Good_Front
Good_Front
Good_Front
Good_Front
Good_Front
Good_Front
Good_Back
Good_Front
Good_Front
Good_Front
Good_Front
Good_Front
Good_Front
Good_Front
Good_Front
Good_Front
Good_Front
Good_Front
Good_Back
Good_Front
Good_Front
Good_Front
Good_Front
Good_Front
Good_Front
Good_Front
Good_Front
Good_Back
Good_Front
Good_Front
Good_Front
Good_Front
Good_Front
Good_Front
Good_Front
Good_Front
Good_Front
Good_Front
Good_Front
Good_Front
Good_Front
Good_Front
Good_Front
Good_Front
Good_Front
Good_Back
Good_Front
Good_Front
Good_Back
Good_Front
Good_Front
Good_Front
Good_Front
Good_Front
Go

C:\Users\Hira\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:947: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)


In [49]:
#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics

# Model Accuracy: how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(test_labels, predicted_label))

Accuracy: 0.8115942028985508


In [50]:
# Model Precision: what percentage of positive tuples are labeled as such?
#print("Precision:",metrics.precision_score(test_labels, predicted_label))

# Model Recall: what percentage of positive tuples are labelled as such?
#print("Recall:",metrics.recall_score(test_labels, predicted_label))

In [ ]:
def plot_decision_function(model):
    _x0 = np.linspace(-5.0, 5.0, 100)
    _x1 = np.linspace(-5.0, 5.0, 100)
    x0, x1 = np.meshgrid(_x0, _x1)
    X = np.c_[x0.ravel(), x1.ravel()]
    y_pred = model.predict(X).reshape(x0.shape)
    y_decision = model.decision_function(X).reshape(x0.shape)
    plt.contourf(x0, x1, y_pred, cmap=plt.cm.brg, alpha=0.2)
    plt.contourf(x0, x1, y_decision,levels=10,alpha=0.3)
 
def plot_dataset(X,y):
    plt.plot(X[:, 0][y==0], X[:, 1][y==0], "bo", ms=10)
    plt.plot(X[:, 0][y==1], X[:, 1][y==1], "r^", ms=10)
    plt.xlabel("A")
    plt.ylabel("B")

In [53]:
#Import svm model
#from sklearn import svm

#Create a svm Classifier
#clf = svm.SVC(kernel='linear') # Linear Kernel

#Train the model using the training sets
#clf.fit(train_data, train_labels)

#Predict the response for test dataset
#y_pred = clf.predict(X_test)

In [54]:
#Import scikit-learn metrics module for accuracy calculation
#from sklearn import metrics

# Model Accuracy: how often is the classifier correct?
#print("Accuracy:",metrics.accuracy_score(test_labels, predicted_label))

In [55]:
# Model Precision: what percentage of positive tuples are labeled as such?
#print("Precision:",metrics.precision_score(test_labels, predicted_label))

# Model Recall: what percentage of positive tuples are labelled as such?
#print("Recall:",metrics.recall_score(test_labels, predicted_label))

In [56]:
#Random Forest (RF) 

In [57]:
clf2 = RandomForestClassifier(n_estimators=1000, max_depth=3,random_state=4)
clf2.fit(train_data, train_labels)

print("Random Forest average score: %f" % clf2.score(test_data, test_labels))

print("")
predicted_label = clf2.predict(test_data)

Accuracy_Score = accuracy_score(test_labels, predicted_label)
Precision_Score = precision_score(test_labels, predicted_label,  average="macro")
Recall_Score = recall_score(test_labels, predicted_label,  average="macro")
F1_Score = f1_score(test_labels, predicted_label,  average="macro")

print('Average Accuracy: %0.2f +/- (%0.1f) %%' % (Accuracy_Score.mean()*100, Accuracy_Score.std()*100))
print('Average Precision: %0.2f +/- (%0.1f) %%' % (Precision_Score.mean()*100, Precision_Score.std()*100))
print('Average Recall: %0.2f +/- (%0.1f) %%' % (Recall_Score.mean()*100, Recall_Score.std()*100))
print('Average F1-Score: %0.2f +/- (%0.1f) %%' % (F1_Score.mean()*100, F1_Score.std()*100))

print("")
#https://en.wikipedia.org/wiki/Confusion_matrix
CM = confusion_matrix(test_labels, predicted_label)

print(CM)

for i in predicted_label:
	print(i)	   

Random Forest average score: 0.985507

Average Accuracy: 98.55 +/- (0.0) %
Average Precision: 98.62 +/- (0.0) %
Average Recall: 97.99 +/- (0.0) %
Average F1-Score: 98.30 +/- (0.0) %

[[189   1]
 [  3  83]]
Good_Back
Good_Back
Good_Back
Good_Back
Good_Back
Good_Back
Good_Back
Good_Back
Good_Back
Good_Back
Good_Back
Good_Back
Good_Back
Good_Back
Good_Back
Good_Back
Good_Back
Good_Back
Good_Back
Good_Back
Good_Back
Good_Back
Good_Back
Good_Back
Good_Back
Good_Back
Good_Back
Good_Back
Good_Back
Good_Back
Good_Back
Good_Back
Good_Back
Good_Back
Good_Back
Good_Back
Good_Back
Good_Back
Good_Back
Good_Back
Good_Back
Good_Back
Good_Back
Good_Back
Good_Back
Good_Back
Good_Back
Good_Back
Good_Back
Good_Back
Good_Back
Good_Back
Good_Back
Good_Back
Good_Back
Good_Back
Good_Back
Good_Back
Good_Back
Good_Back
Good_Back
Good_Back
Good_Back
Good_Back
Good_Back
Good_Back
Good_Back
Good_Back
Good_Back
Good_Back
Good_Back
Good_Back
Good_Back
Good_Back
Good_Back
Good_Back
Good_Back
Good_Back
Good_Back
Good

In [58]:
#Import scikit-learn metrics module for accuracy calculation
#from sklearn import metrics

# Model Accuracy: how often is the classifier correct?
#print("Accuracy:",metrics.accuracy_score(test_labels, predicted_label))

In [59]:
#Naïve Bayes (NB) 

In [60]:
nb= GaussianNB()
nb.fit(train_data, train_labels)
print("NB average score: %f" % nb.score(test_data, test_labels))
print("")
predicted_label = nb.predict(test_data)

Accuracy_Score = accuracy_score(test_labels, predicted_label)
Precision_Score = precision_score(test_labels, predicted_label,  average="macro")
Recall_Score = recall_score(test_labels, predicted_label,  average="macro")
F1_Score = f1_score(test_labels, predicted_label,  average="macro")

print('Average Accuracy: %0.2f +/- (%0.1f) %%' % (Accuracy_Score.mean()*100, Accuracy_Score.std()*100))
print('Average Precision: %0.2f +/- (%0.1f) %%' % (Precision_Score.mean()*100, Precision_Score.std()*100))
print('Average Recall: %0.2f +/- (%0.1f) %%' % (Recall_Score.mean()*100, Recall_Score.std()*100))
print('Average F1-Score: %0.2f +/- (%0.1f) %%' % (F1_Score.mean()*100, F1_Score.std()*100))

print("")
#https://en.wikipedia.org/wiki/Confusion_matrix
CM = confusion_matrix(test_labels, predicted_label)

print(CM)

for i in predicted_label:
	print(i)	   

NB average score: 0.844203

Average Accuracy: 84.42 +/- (0.0) %
Average Precision: 82.94 +/- (0.0) %
Average Recall: 88.05 +/- (0.0) %
Average F1-Score: 83.51 +/- (0.0) %

[[149  41]
 [  2  84]]
Peaberry_Back
Good_Back
Good_Back
Good_Back
Good_Back
Good_Back
Good_Back
Peaberry_Back
Good_Back
Good_Back
Good_Back
Good_Back
Good_Back
Peaberry_Back
Peaberry_Back
Good_Back
Good_Back
Good_Back
Peaberry_Back
Peaberry_Back
Good_Back
Good_Back
Good_Back
Good_Back
Peaberry_Back
Peaberry_Back
Good_Back
Good_Back
Peaberry_Back
Good_Back
Peaberry_Back
Peaberry_Back
Good_Back
Good_Back
Peaberry_Back
Peaberry_Back
Good_Back
Good_Back
Good_Back
Good_Back
Peaberry_Back
Good_Back
Good_Back
Good_Back
Good_Back
Good_Back
Good_Back
Good_Back
Good_Back
Peaberry_Back
Peaberry_Back
Good_Back
Good_Back
Good_Back
Good_Back
Good_Back
Peaberry_Back
Peaberry_Back
Good_Back
Good_Back
Good_Back
Good_Back
Good_Back
Peaberry_Back
Good_Back
Good_Back
Good_Back
Good_Back
Good_Back
Good_Back
Good_Back
Good_Back
Peaberry_

In [61]:
#Import scikit-learn metrics module for accuracy calculation
#from sklearn import metrics

# Model Accuracy: how often is the classifier correct?
#print("Accuracy:",metrics.accuracy_score(test_labels, predicted_label))

In [62]:
#Multilayer Perceptron (MLP) 

In [63]:
mlp= MLPClassifier()
mlp.fit(train_data, train_labels)
print("MLP average score: %f" % mlp.score(test_data, test_labels))
print("")
predicted_label = mlp.predict(test_data)

Accuracy_Score = accuracy_score(test_labels, predicted_label)
Precision_Score = precision_score(test_labels, predicted_label,  average="macro")
Recall_Score = recall_score(test_labels, predicted_label,  average="macro")
F1_Score = f1_score(test_labels, predicted_label,  average="macro")

print('Average Accuracy: %0.2f +/- (%0.1f) %%' % (Accuracy_Score.mean()*100, Accuracy_Score.std()*100))
print('Average Precision: %0.2f +/- (%0.1f) %%' % (Precision_Score.mean()*100, Precision_Score.std()*100))
print('Average Recall: %0.2f +/- (%0.1f) %%' % (Recall_Score.mean()*100, Recall_Score.std()*100))
print('Average F1-Score: %0.2f +/- (%0.1f) %%' % (F1_Score.mean()*100, F1_Score.std()*100))

print("")
#https://en.wikipedia.org/wiki/Confusion_matrix
CM = confusion_matrix(test_labels, predicted_label)

print(CM)

for i in predicted_label:
	print(i)	   

MLP average score: 0.826087

Average Accuracy: 82.61 +/- (0.0) %
Average Precision: 79.62 +/- (0.0) %
Average Recall: 81.32 +/- (0.0) %
Average F1-Score: 80.33 +/- (0.0) %

[[161  29]
 [ 19  67]]
Peaberry_Back
Good_Back
Good_Back
Good_Back
Good_Back
Peaberry_Back
Peaberry_Back
Good_Back
Peaberry_Back
Peaberry_Back
Good_Back
Good_Back
Good_Back
Good_Back
Peaberry_Back
Good_Back
Good_Back
Good_Back
Good_Back
Peaberry_Back
Peaberry_Back
Good_Back
Good_Back
Good_Back
Peaberry_Back
Good_Back
Good_Back
Good_Back
Good_Back
Good_Back
Peaberry_Back
Good_Back
Good_Back
Good_Back
Good_Back
Good_Back
Good_Back
Good_Back
Good_Back
Good_Back
Peaberry_Back
Good_Back
Good_Back
Good_Back
Good_Back
Good_Back
Good_Back
Peaberry_Back
Good_Back
Good_Back
Peaberry_Back
Good_Back
Good_Back
Peaberry_Back
Good_Back
Good_Back
Peaberry_Back
Peaberry_Back
Good_Back
Good_Back
Good_Back
Good_Back
Good_Back
Good_Back
Good_Back
Good_Back
Good_Back
Good_Back
Good_Back
Good_Back
Good_Back
Good_Back
Peaberry_Back
Peaber

In [64]:
#Import scikit-learn metrics module for accuracy calculation
#from sklearn import metrics

# Model Accuracy: how often is the classifier correct?
#print("Accuracy:",metrics.accuracy_score(test_labels, predicted_label))

In [67]:
#Import scikit-learn metrics module for accuracy calculation
#from sklearn import metrics

# Model Accuracy: how often is the classifier correct?
#print("Accuracy:",metrics.accuracy_score(test_labels, predicted_label))